find_package(absl CONFIG REQUIRED)
find_package(asio-grpc CONFIG REQUIRED)
find_package(OpenSSL CONFIG REQUIRED)
find_package(CURL CONFIG REQUIRED)
find_package(flatbuffers CONFIG REQUIRED)
find_package(fmt CONFIG REQUIRED)
find_package(gflags CONFIG REQUIRED)
find_package(GTest CONFIG REQUIRED)
find_package(gRPC CONFIG REQUIRED)
find_package(gtest-parallel CONFIG REQUIRED)
find_package(jemalloc CONFIG REQUIRED)
find_package(nlohmann_json CONFIG REQUIRED)
find_package(unifex CONFIG REQUIRED)
find_package(libfuse CONFIG REQUIRED)
find_package(libunwind CONFIG REQUIRED)
# find_package(ZLIB CONFIG REQUIRED)
set(protobuf_MODULE_COMPATIBLE ON)
find_package(Protobuf CONFIG REQUIRED)
set(Protobuf_INCLUDE_DIR ${Protobuf_INCLUDE_DIRS})
find_package(opentelemetry-cpp CONFIG REQUIRED)
find_package(prometheus-cpp CONFIG REQUIRED)
find_package(quill CONFIG REQUIRED)
find_package(zstd CONFIG REQUIRED)
get_target_property(ZSTD_INCLUDE_DIRS zstd::libzstd
                    INTERFACE_INCLUDE_DIRECTORIES)
get_target_property(ZSTD_LIBRARIES zstd::libzstd INTERFACE_LINK_LIBRARIES)
# RocksDB depends on `zstd::zstd`, but Zstandard only provides `zstd::libzstd`.
# Create an alias to map `zstd::zstd` to `zstd::libzstd` for compatibility.
add_library(zstd::zstd ALIAS zstd::libzstd)
find_package(Snappy CONFIG REQUIRED)
find_package(RocksDB CONFIG REQUIRED)
